version: "3.1"

services:
  security-api:
    image: ${IMAGE_API:-ghcr.io/maxiguerrero/marketplace/main/security-api:latest}
    deploy:
      resources:
        limits:
          memory: 512M
    container_name: security-api
    restart: always
    ports:
      - 8080:8080
    environment:
      - DATABASE='marketplace'
      - COST_ALGORITHMIC='10'
      - DB_CONNECTION=${DB_CONNECTION}
    networks:
      - marketplace

networks:
  marketplace:
    external: true
