version: "3.1"

services:
  security-api:
    image: ${IMAGE_API:-ghcr.io/maxiguerrero/marketplace/main/security-api:latest}
    deploy:
      resources:
        limits:
          memory: 512M
    container_name: security-api
    restart: always
    ports:
      - 8080:8080
    environment:
      - DATABASE='marketplace'
      - COST_ALGORITHMIC='10'
      - DB_CONNECTION=${DB_CONNECTION:-mongoserver}
    networks:
      - marketplace

  stock-api:
    image: ${IMAGE_API:-ghcr.io/maxiguerrero/marketplace/main/stocks-api:latest}
    deploy:
      resources:
        limits:
          memory: 512M
    container_name: stock-api
    restart: always
    ports:
      - 8080:8080
    environment:
      - DATABASE='marketplace'
      - DB_CONNECTION=${DB_CONNECTION:-mongoserver}
      - SECURITY_API_URL='http://security-api:8080'
      - SECURE='true'
    networks:
      - marketplace

networks:
  marketplace:
    external: true
