name: Pipeline - Payment API
run-name: "[payment-api]${{ github.actor }} has made changes on branch ${{ github.ref_name }}"
on:
  push:
    branches:
      - main
    paths:
      - "payment-api/**"
      - ".github/workflows/**"
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [lts/*]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - run: npm ci
        working-directory: payment-api
      - run: npm run lint
        working-directory: payment-api

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [lts/*]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - run: npm ci
        working-directory: payment-api
      - run: npm run test
        working-directory: payment-api

  release-image:
    if: ${{github.ref_name}} == 'main' && ${{github.event_name}} == 'push'
    needs: [lint, test]
    runs-on: ubuntu-latest
    env:
      IMAGE_URL: ghcr.io/maxiguerrero/marketplace/${{ github.ref_name }}/payment-api:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to github repository
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build docker image
        run: docker build -t ${{ env.IMAGE_URL }} ./payment-api/
      - name: publish docker image
        run: docker push ${{ env.IMAGE_URL }}
